name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyJWT==2.8.0 

      # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify your Python version here

    # Step 4: Run tests
    - name: Run tests
      run: |
        python -m unittest tests/client_tests.py  # Assumes tests are in the "tests" directory
